# Generated by Django 5.1.2 on 2024-10-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'ItemGroup',
                'verbose_name_plural': 'ItemGroups',
            },
        ),
    ]
