# Generated by Django 5.1.2 on 2024-10-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=40)),
                ('itemPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemUnit', models.CharField(choices=[('kg', 'kilogram'), ('lt', 'ltre'), ('lt', 'liter'), ('bx', 'box'), ('tk', 'tank')], max_length=2)),
                ('itemGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.itemgroup')),
            ],
        ),
    ]
